#!/bin/bash

MODELSIM_PATH="../../ModelSim"

for file in test_assemblies/*.s; do
    filepath="$pwd/${file##*/}"
    python ../assembler/assembler.py "$file" -o "./test_binaries/${filepath%.s}.o"
done
