#!/bin/bash

source ./init.sh

# Runs assemble then select on the name
# Check if the correct number of arguments are provided
if [ "$#" -ne 1 ]; then
    echo "Usage: ./go <filename>"
    exit 1
fi

file=$1
python ../assembler/assembler.py "./test_assemblies/$file.s" "./test_binaries/$file.o"

source ./select "$file.o"